[[gat]]
arch = "aarch64"
git-tree-sha1 = "c18e839d43dc7da4cd56557d1d0295eeaba8501a"
os = "macos"

    [[gat.download]]
    sha256 = "bde0187d28446720550228d74fbb6a9462da96d851b3323ca8e0a49b212f85fb"
    url = "https://github.com/terasakisatoshi/gat_jll.jl/releases/download/gat-v0.0.1+0/gat.v0.0.1.aarch64-apple-darwin.tar.gz"
[[gat]]
arch = "aarch64"
git-tree-sha1 = "7106be44a1173a9b9025805c55c48fef744fd04d"
libc = "glibc"
os = "linux"

    [[gat.download]]
    sha256 = "903db605bd71b81963f522480871c56248799db7ca35bea2ec1eff387d40751b"
    url = "https://github.com/terasakisatoshi/gat_jll.jl/releases/download/gat-v0.0.1+0/gat.v0.0.1.aarch64-linux-gnu.tar.gz"
[[gat]]
arch = "aarch64"
git-tree-sha1 = "7106be44a1173a9b9025805c55c48fef744fd04d"
libc = "musl"
os = "linux"

    [[gat.download]]
    sha256 = "903db605bd71b81963f522480871c56248799db7ca35bea2ec1eff387d40751b"
    url = "https://github.com/terasakisatoshi/gat_jll.jl/releases/download/gat-v0.0.1+0/gat.v0.0.1.aarch64-linux-musl.tar.gz"
[[gat]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "76c2b370a6822c2022e12e727a62e9a10e82fb3b"
libc = "glibc"
os = "linux"

    [[gat.download]]
    sha256 = "0dd62df2c8633ef33d6f7719483690001101ec0049d3f7c52b57eb59a338785b"
    url = "https://github.com/terasakisatoshi/gat_jll.jl/releases/download/gat-v0.0.1+0/gat.v0.0.1.armv6l-linux-gnueabihf.tar.gz"
[[gat]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "76c2b370a6822c2022e12e727a62e9a10e82fb3b"
libc = "musl"
os = "linux"

    [[gat.download]]
    sha256 = "0dd62df2c8633ef33d6f7719483690001101ec0049d3f7c52b57eb59a338785b"
    url = "https://github.com/terasakisatoshi/gat_jll.jl/releases/download/gat-v0.0.1+0/gat.v0.0.1.armv6l-linux-musleabihf.tar.gz"
[[gat]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "d4836eeb9fb2854f977d221f9e4b5f4b77a80a17"
libc = "glibc"
os = "linux"

    [[gat.download]]
    sha256 = "9482095bd080d0c253c1475de526062d4599ae61df22b6ed6a305f64688797e0"
    url = "https://github.com/terasakisatoshi/gat_jll.jl/releases/download/gat-v0.0.1+0/gat.v0.0.1.armv7l-linux-gnueabihf.tar.gz"
[[gat]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "d4836eeb9fb2854f977d221f9e4b5f4b77a80a17"
libc = "musl"
os = "linux"

    [[gat.download]]
    sha256 = "9482095bd080d0c253c1475de526062d4599ae61df22b6ed6a305f64688797e0"
    url = "https://github.com/terasakisatoshi/gat_jll.jl/releases/download/gat-v0.0.1+0/gat.v0.0.1.armv7l-linux-musleabihf.tar.gz"
[[gat]]
arch = "i686"
git-tree-sha1 = "88914752d66edb7c3d9a43d5fad5c1f3b1426ca6"
libc = "glibc"
os = "linux"

    [[gat.download]]
    sha256 = "d1180f30336e229e89ac4f41ca0ab711a84347e6f2df1c5e18a03f67c0da8f09"
    url = "https://github.com/terasakisatoshi/gat_jll.jl/releases/download/gat-v0.0.1+0/gat.v0.0.1.i686-linux-gnu.tar.gz"
[[gat]]
arch = "i686"
git-tree-sha1 = "88914752d66edb7c3d9a43d5fad5c1f3b1426ca6"
libc = "musl"
os = "linux"

    [[gat.download]]
    sha256 = "d1180f30336e229e89ac4f41ca0ab711a84347e6f2df1c5e18a03f67c0da8f09"
    url = "https://github.com/terasakisatoshi/gat_jll.jl/releases/download/gat-v0.0.1+0/gat.v0.0.1.i686-linux-musl.tar.gz"
[[gat]]
arch = "i686"
git-tree-sha1 = "55a5328186387c0f42d95731a78b1ce4b88b9986"
os = "windows"

    [[gat.download]]
    sha256 = "a15d4c85dd9d837ed72ff6188ee27a9bd46d599ffbe0752d7e8a6150f88588db"
    url = "https://github.com/terasakisatoshi/gat_jll.jl/releases/download/gat-v0.0.1+0/gat.v0.0.1.i686-w64-mingw32.tar.gz"
[[gat]]
arch = "powerpc64le"
git-tree-sha1 = "d37fd33abab5ddaedead7655c2de03ea5555780d"
libc = "glibc"
os = "linux"

    [[gat.download]]
    sha256 = "9ba943432aafd635a5dac11e93d9d9fb0cd2b5ff49b16834d10cdf51fcaeaec6"
    url = "https://github.com/terasakisatoshi/gat_jll.jl/releases/download/gat-v0.0.1+0/gat.v0.0.1.powerpc64le-linux-gnu.tar.gz"
[[gat]]
arch = "x86_64"
git-tree-sha1 = "04b59e7945f0c01120c15f92b0dccf883818f4df"
os = "macos"

    [[gat.download]]
    sha256 = "85f8e4de5cc49c545cb8d9a9def1bf8e613ff3d707919fb3f8105cb1bf4d4050"
    url = "https://github.com/terasakisatoshi/gat_jll.jl/releases/download/gat-v0.0.1+0/gat.v0.0.1.x86_64-apple-darwin.tar.gz"
[[gat]]
arch = "x86_64"
git-tree-sha1 = "f44a57989bdf8d4bae34b19e774991aeaf3ff560"
libc = "glibc"
os = "linux"

    [[gat.download]]
    sha256 = "f28c144ba114bedaaa71716eb0a7b03d65e6d7995b72def379de5f33a485104c"
    url = "https://github.com/terasakisatoshi/gat_jll.jl/releases/download/gat-v0.0.1+0/gat.v0.0.1.x86_64-linux-gnu.tar.gz"
[[gat]]
arch = "x86_64"
git-tree-sha1 = "bc35fa184f8023b32756c1e081ba3ad2f3341bf4"
libc = "musl"
os = "linux"

    [[gat.download]]
    sha256 = "dbc14c9b8cb479f99d38a357603d3829cc19d8e1b6c5c5114aa0d40a4e67ffe6"
    url = "https://github.com/terasakisatoshi/gat_jll.jl/releases/download/gat-v0.0.1+0/gat.v0.0.1.x86_64-linux-musl.tar.gz"
[[gat]]
arch = "x86_64"
git-tree-sha1 = "cbba58bd09ee793ec58747f047495e654b1ae4bf"
os = "freebsd"

    [[gat.download]]
    sha256 = "dfac5b34d143020555bdbeb3eff5f608897c58b7595766443922a50cc5d2c075"
    url = "https://github.com/terasakisatoshi/gat_jll.jl/releases/download/gat-v0.0.1+0/gat.v0.0.1.x86_64-unknown-freebsd.tar.gz"
[[gat]]
arch = "x86_64"
git-tree-sha1 = "9f7b8bc2146797a3e48310fc319f59be6049d0bf"
os = "windows"

    [[gat.download]]
    sha256 = "348642a662c4f2997f2af7acecf5ad137ecccbf718a73067c271991c85fceef9"
    url = "https://github.com/terasakisatoshi/gat_jll.jl/releases/download/gat-v0.0.1+0/gat.v0.0.1.x86_64-w64-mingw32.tar.gz"
