[[gat]]
arch = "aarch64"
git-tree-sha1 = "6e1de2636fa6b1059d28e6e5dc2fc1b459e4494b"
os = "macos"

    [[gat.download]]
    sha256 = "b46462082566c86f35068ac1a9a22847be5d8d4df52f1bdd77d0eb91bee49957"
    url = "https://github.com/terasakisatoshi/gat_jll.jl/releases/download/gat-v0.19.1+0/gat.v0.19.1.aarch64-apple-darwin.tar.gz"
[[gat]]
arch = "aarch64"
git-tree-sha1 = "44320c12316bb524d87aceb008273919d125ea6a"
libc = "glibc"
os = "linux"

    [[gat.download]]
    sha256 = "01673487a3e5313545296b4694739e081ea9b15d466a1521b574b9c474a796a3"
    url = "https://github.com/terasakisatoshi/gat_jll.jl/releases/download/gat-v0.19.1+0/gat.v0.19.1.aarch64-linux-gnu.tar.gz"
[[gat]]
arch = "aarch64"
git-tree-sha1 = "44320c12316bb524d87aceb008273919d125ea6a"
libc = "musl"
os = "linux"

    [[gat.download]]
    sha256 = "01673487a3e5313545296b4694739e081ea9b15d466a1521b574b9c474a796a3"
    url = "https://github.com/terasakisatoshi/gat_jll.jl/releases/download/gat-v0.19.1+0/gat.v0.19.1.aarch64-linux-musl.tar.gz"
[[gat]]
arch = "aarch64"
git-tree-sha1 = "b4a9716be9e0d7c8858a2a3fbd167abbea05517e"
os = "freebsd"

    [[gat.download]]
    sha256 = "1ec0aa6c2ccaece8f274d3d10ce8f5b3b2668beaf53d510e3752d0632525cca1"
    url = "https://github.com/terasakisatoshi/gat_jll.jl/releases/download/gat-v0.19.1+0/gat.v0.19.1.aarch64-unknown-freebsd.tar.gz"
[[gat]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "92084e3f93e66ee022599fcdf2a2b7b6fadbc8ee"
libc = "glibc"
os = "linux"

    [[gat.download]]
    sha256 = "3febde8b147c7f802f055ec87fa9aefc64f75960988bc6a08759cbeb8505cb4f"
    url = "https://github.com/terasakisatoshi/gat_jll.jl/releases/download/gat-v0.19.1+0/gat.v0.19.1.armv6l-linux-gnueabihf.tar.gz"
[[gat]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "92084e3f93e66ee022599fcdf2a2b7b6fadbc8ee"
libc = "musl"
os = "linux"

    [[gat.download]]
    sha256 = "3febde8b147c7f802f055ec87fa9aefc64f75960988bc6a08759cbeb8505cb4f"
    url = "https://github.com/terasakisatoshi/gat_jll.jl/releases/download/gat-v0.19.1+0/gat.v0.19.1.armv6l-linux-musleabihf.tar.gz"
[[gat]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "0b2d3e141ed649da76116c43a3c9704b99417d72"
libc = "glibc"
os = "linux"

    [[gat.download]]
    sha256 = "d0e13208dce7627ea68da989bc4a34933ef8a2d722b135c40437956a6d9ca95e"
    url = "https://github.com/terasakisatoshi/gat_jll.jl/releases/download/gat-v0.19.1+0/gat.v0.19.1.armv7l-linux-gnueabihf.tar.gz"
[[gat]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "0b2d3e141ed649da76116c43a3c9704b99417d72"
libc = "musl"
os = "linux"

    [[gat.download]]
    sha256 = "d0e13208dce7627ea68da989bc4a34933ef8a2d722b135c40437956a6d9ca95e"
    url = "https://github.com/terasakisatoshi/gat_jll.jl/releases/download/gat-v0.19.1+0/gat.v0.19.1.armv7l-linux-musleabihf.tar.gz"
[[gat]]
arch = "i686"
git-tree-sha1 = "e3adf0940bf40f101ef44e1b49b0e917953efbee"
libc = "glibc"
os = "linux"

    [[gat.download]]
    sha256 = "74a775a977b2e49fa599ea09105f23ab30d00c35545f601b16ba6272904a1ad8"
    url = "https://github.com/terasakisatoshi/gat_jll.jl/releases/download/gat-v0.19.1+0/gat.v0.19.1.i686-linux-gnu.tar.gz"
[[gat]]
arch = "i686"
git-tree-sha1 = "e3adf0940bf40f101ef44e1b49b0e917953efbee"
libc = "musl"
os = "linux"

    [[gat.download]]
    sha256 = "74a775a977b2e49fa599ea09105f23ab30d00c35545f601b16ba6272904a1ad8"
    url = "https://github.com/terasakisatoshi/gat_jll.jl/releases/download/gat-v0.19.1+0/gat.v0.19.1.i686-linux-musl.tar.gz"
[[gat]]
arch = "i686"
git-tree-sha1 = "9e999069fcb23f67fab56844a91c98a0f317c3c4"
os = "windows"

    [[gat.download]]
    sha256 = "83507852559c76a15159b2062951c90a7970f253fa760389da12aafd06fbbf88"
    url = "https://github.com/terasakisatoshi/gat_jll.jl/releases/download/gat-v0.19.1+0/gat.v0.19.1.i686-w64-mingw32.tar.gz"
[[gat]]
arch = "powerpc64le"
git-tree-sha1 = "c7518e673e92ac0ae32c10e6ce328ab78acd2276"
libc = "glibc"
os = "linux"

    [[gat.download]]
    sha256 = "8de95c1435d6f127a278dd895a4d6d4480120ac0ac7f1c668c34d3f1e5656eaf"
    url = "https://github.com/terasakisatoshi/gat_jll.jl/releases/download/gat-v0.19.1+0/gat.v0.19.1.powerpc64le-linux-gnu.tar.gz"
[[gat]]
arch = "x86_64"
git-tree-sha1 = "a11bb9978c0e5580ddf87cd5a9380ff1291bde9a"
os = "macos"

    [[gat.download]]
    sha256 = "656a100ca566712c60db62ce74f748c8608d98c7b778d903db058ec7371f4d59"
    url = "https://github.com/terasakisatoshi/gat_jll.jl/releases/download/gat-v0.19.1+0/gat.v0.19.1.x86_64-apple-darwin.tar.gz"
[[gat]]
arch = "x86_64"
git-tree-sha1 = "a17b0e50957a9c90c62110700346ad3b57a900b9"
libc = "glibc"
os = "linux"

    [[gat.download]]
    sha256 = "126e985e06b5ce0cc829d991ef7bfe9bf63d7ed6d3c7ce34300dd76f41740cc6"
    url = "https://github.com/terasakisatoshi/gat_jll.jl/releases/download/gat-v0.19.1+0/gat.v0.19.1.x86_64-linux-gnu.tar.gz"
[[gat]]
arch = "x86_64"
git-tree-sha1 = "967cd1681027f2cee8c335ac5c7e845940ce537d"
libc = "musl"
os = "linux"

    [[gat.download]]
    sha256 = "57d4f961906f0dcc2b95313c8dbc3a6547ae2b80868bac63a659f5335d2f0e9a"
    url = "https://github.com/terasakisatoshi/gat_jll.jl/releases/download/gat-v0.19.1+0/gat.v0.19.1.x86_64-linux-musl.tar.gz"
[[gat]]
arch = "x86_64"
git-tree-sha1 = "1a311e1f4709e973557e6880a481c5c3d2c7eaac"
os = "freebsd"

    [[gat.download]]
    sha256 = "8b1cc526c17da17d133251b151c99e171fc180470a76a25e0f855d2d7acf051f"
    url = "https://github.com/terasakisatoshi/gat_jll.jl/releases/download/gat-v0.19.1+0/gat.v0.19.1.x86_64-unknown-freebsd.tar.gz"
[[gat]]
arch = "x86_64"
git-tree-sha1 = "c8ad3b2a25d5df52161aebb6a592cd4162e4346e"
os = "windows"

    [[gat.download]]
    sha256 = "aa05da646047f962bb64adde26a276f49a9624b97bcbf52144303b27749eff25"
    url = "https://github.com/terasakisatoshi/gat_jll.jl/releases/download/gat-v0.19.1+0/gat.v0.19.1.x86_64-w64-mingw32.tar.gz"
