[[gat]]
arch = "aarch64"
git-tree-sha1 = "78b16b4c3fa09476e840e51c0711b8ad5f97d2c1"
os = "macos"

    [[gat.download]]
    sha256 = "b6d521ffba970fd8c3de9ebf7ad0e70832f9a2901f255116fa160f1f5c5515ff"
    url = "https://github.com/terasakisatoshi/gat_jll.jl/releases/download/gat-v0.0.1+0/gat.v0.0.1.aarch64-apple-darwin.tar.gz"
[[gat]]
arch = "aarch64"
git-tree-sha1 = "96350897ec08102469dca2126c6724aeb6cf29d1"
libc = "glibc"
os = "linux"

    [[gat.download]]
    sha256 = "ca00aac51b91eb3fb5421424d0d58cae5356d8cfe544fef63331084695c82a18"
    url = "https://github.com/terasakisatoshi/gat_jll.jl/releases/download/gat-v0.0.1+0/gat.v0.0.1.aarch64-linux-gnu.tar.gz"
[[gat]]
arch = "aarch64"
git-tree-sha1 = "96350897ec08102469dca2126c6724aeb6cf29d1"
libc = "musl"
os = "linux"

    [[gat.download]]
    sha256 = "ca00aac51b91eb3fb5421424d0d58cae5356d8cfe544fef63331084695c82a18"
    url = "https://github.com/terasakisatoshi/gat_jll.jl/releases/download/gat-v0.0.1+0/gat.v0.0.1.aarch64-linux-musl.tar.gz"
[[gat]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "39040e599d56c2e96cb05f1bd92944328e8ad519"
libc = "glibc"
os = "linux"

    [[gat.download]]
    sha256 = "1d67ccb869aa5577b90fb024709c5c004d964230b94fdaf46b2e6825a01ab4bc"
    url = "https://github.com/terasakisatoshi/gat_jll.jl/releases/download/gat-v0.0.1+0/gat.v0.0.1.armv6l-linux-gnueabihf.tar.gz"
[[gat]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "39040e599d56c2e96cb05f1bd92944328e8ad519"
libc = "musl"
os = "linux"

    [[gat.download]]
    sha256 = "1d67ccb869aa5577b90fb024709c5c004d964230b94fdaf46b2e6825a01ab4bc"
    url = "https://github.com/terasakisatoshi/gat_jll.jl/releases/download/gat-v0.0.1+0/gat.v0.0.1.armv6l-linux-musleabihf.tar.gz"
[[gat]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "f4b9333c12807562d7f05c00ca4af1be5e2e82f8"
libc = "glibc"
os = "linux"

    [[gat.download]]
    sha256 = "ff3741bad78a759ffcb71f456ba3969a3c2d59634af9a66c414ec47176605a1f"
    url = "https://github.com/terasakisatoshi/gat_jll.jl/releases/download/gat-v0.0.1+0/gat.v0.0.1.armv7l-linux-gnueabihf.tar.gz"
[[gat]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "f4b9333c12807562d7f05c00ca4af1be5e2e82f8"
libc = "musl"
os = "linux"

    [[gat.download]]
    sha256 = "ff3741bad78a759ffcb71f456ba3969a3c2d59634af9a66c414ec47176605a1f"
    url = "https://github.com/terasakisatoshi/gat_jll.jl/releases/download/gat-v0.0.1+0/gat.v0.0.1.armv7l-linux-musleabihf.tar.gz"
[[gat]]
arch = "i686"
git-tree-sha1 = "06ecaeef089d016624ae8911a1ab2c48f0e9b9e7"
libc = "glibc"
os = "linux"

    [[gat.download]]
    sha256 = "cff3af8caf607151bc80d28df4fd9a7e6d8f1f76746a5836f8700ab51947bc84"
    url = "https://github.com/terasakisatoshi/gat_jll.jl/releases/download/gat-v0.0.1+0/gat.v0.0.1.i686-linux-gnu.tar.gz"
[[gat]]
arch = "i686"
git-tree-sha1 = "06ecaeef089d016624ae8911a1ab2c48f0e9b9e7"
libc = "musl"
os = "linux"

    [[gat.download]]
    sha256 = "cff3af8caf607151bc80d28df4fd9a7e6d8f1f76746a5836f8700ab51947bc84"
    url = "https://github.com/terasakisatoshi/gat_jll.jl/releases/download/gat-v0.0.1+0/gat.v0.0.1.i686-linux-musl.tar.gz"
[[gat]]
arch = "i686"
git-tree-sha1 = "3f45f45fd9302bc9400e05a74c170329ce9d85ad"
os = "windows"

    [[gat.download]]
    sha256 = "a62e2cf56e6b5047bd1a9c239fae4af103e138f7b241b1b682e6dc5e9062cf98"
    url = "https://github.com/terasakisatoshi/gat_jll.jl/releases/download/gat-v0.0.1+0/gat.v0.0.1.i686-w64-mingw32.tar.gz"
[[gat]]
arch = "powerpc64le"
git-tree-sha1 = "7f02384f5b4e2a4187f1a016e3fd50a092cd9cae"
libc = "glibc"
os = "linux"

    [[gat.download]]
    sha256 = "cddacfa89f322e82b808f3f9321f0540aa13982524bdd2930078de4d17ca103b"
    url = "https://github.com/terasakisatoshi/gat_jll.jl/releases/download/gat-v0.0.1+0/gat.v0.0.1.powerpc64le-linux-gnu.tar.gz"
[[gat]]
arch = "x86_64"
git-tree-sha1 = "d98646e614b152b3bc13d527c72b87931c7a1145"
os = "macos"

    [[gat.download]]
    sha256 = "7755e9aa55b7dda5ceb014cc581859780c19eda15a50867cdb238b30f379db60"
    url = "https://github.com/terasakisatoshi/gat_jll.jl/releases/download/gat-v0.0.1+0/gat.v0.0.1.x86_64-apple-darwin.tar.gz"
[[gat]]
arch = "x86_64"
git-tree-sha1 = "ffb7d9b66f08c225ed95bfdd3592c721ac77c0dd"
libc = "glibc"
os = "linux"

    [[gat.download]]
    sha256 = "9ea1c0515e340e2fa4f174b2e627cfd4ad76c496362797985aba35c9d18d7da3"
    url = "https://github.com/terasakisatoshi/gat_jll.jl/releases/download/gat-v0.0.1+0/gat.v0.0.1.x86_64-linux-gnu.tar.gz"
[[gat]]
arch = "x86_64"
git-tree-sha1 = "2278211b4592ee56810d5cd914f98b13af8a944e"
libc = "musl"
os = "linux"

    [[gat.download]]
    sha256 = "5eac4f36d907fa9176b860f27f8e47884db4c74f3e3f5809b84c8e3f9377fd4f"
    url = "https://github.com/terasakisatoshi/gat_jll.jl/releases/download/gat-v0.0.1+0/gat.v0.0.1.x86_64-linux-musl.tar.gz"
[[gat]]
arch = "x86_64"
git-tree-sha1 = "f29a72f18fe4ef094eaa76c9bf08080723f4e72a"
os = "freebsd"

    [[gat.download]]
    sha256 = "908ef7bb5c62883d35a5b6e4dcab559d9c1a666223b92d49866126d05d565ae6"
    url = "https://github.com/terasakisatoshi/gat_jll.jl/releases/download/gat-v0.0.1+0/gat.v0.0.1.x86_64-unknown-freebsd.tar.gz"
[[gat]]
arch = "x86_64"
git-tree-sha1 = "f0a386eb7e6558823c4526da5be6430747eec9b7"
os = "windows"

    [[gat.download]]
    sha256 = "dee0ae032f7893a31c4b94a02ce40304b591af38e80c5cf98f9d90f6008ddad9"
    url = "https://github.com/terasakisatoshi/gat_jll.jl/releases/download/gat-v0.0.1+0/gat.v0.0.1.x86_64-w64-mingw32.tar.gz"
