# Autogenerated wrapper script for gat_jll for aarch64-linux-gnu
export gat

JLLWrappers.@generate_wrapper_header("gat")
JLLWrappers.@declare_executable_product(gat)
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_executable_product(
        gat,
        "bin/gat",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
