# Autogenerated wrapper script for gat_jll for i686-w64-mingw32
export gat

JLLWrappers.@generate_wrapper_header("gat")
JLLWrappers.@declare_executable_product(gat)
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_executable_product(
        gat,
        "bin\\gat.exe",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
